highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: https://shreyakhurana.github.io/vitae
author: Shreya Khurana

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Shreya Khurana's Resume
name: Shreya Khurana
email: shreyak4@illinois.edu
email_full: mailto:shreyak4@illinois.edu
website: shreyakhurana.github.io
website_full: https://shreyakhurana.github.io
github: ShreyaKhurana
twitter: twitter
tel:
tel_full:
google_maps:
address:
  street:
  postcode:
  city:
  country:
google_analytics:

# needed for travis-ci build
exclude: [vendor]
